import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const guests = [
    { name: 'Marina Bromo', email: null },
    { name: 'Paolo Sicignano', email: null },
    { name: 'Matteo Sicignano', email: null },
    { name: 'Dario Romboli', email: null },
    { name: 'Diletta Menichetti', email: null },
    { name: 'Marta Cheli', email: null },
    { name: 'Andrea Ghelardoni', email: null },
    { name: 'Francesca Rose', email: null },
    { name: 'Edoardo Papiani', email: null },
    { name: 'Giulio Papiani', email: null },
    { name: 'Alice Medda', email: null },
    { name: 'Alessandra Fuligni', email: null },
    { name: 'Francesco Mannino', email: null },
    { name: 'Beatrice Ballabio', email: null },
    { name: 'Paolo Campari', email: null },
    { name: 'Davide Brignoli', email: null },
    { name: 'Sara Morandini', email: null },
    { name: 'Jacopo Guerini', email: null },
    { name: 'Emanuele Zaccaria', email: null },
    { name: 'Fernando Carta', email: null },
    { name: 'Simone Lucarelli', email: null },
    { name: 'Rima Njem', email: null },
    { name: 'Francesco Santantonio', email: null },
    { name: 'Martina Zampini', email: null },
    { name: 'Guido Provvidenza', email: null },
    { name: 'Benedetta Costanzi', email: null },
    { name: 'Martina Marcantelli', email: null },
    { name: 'Gabriele Bindi', email: null },
    { name: 'Barbanera', email: null },
    { name: 'Mamo', email: null },
    { name: 'Pineta', email: null },
    { name: 'Tasso', email: null },
    { name: 'Mirko Sorriso', email: null },
    { name: 'Amy Borragine', email: null },
    { name: 'Valerio Urbani', email: null },
    { name: 'Gabriele Cavalletti', email: null },
    { name: 'Elena Grazioli', email: null },
    { name: 'Giulio Tarlati', email: null },
    { name: 'Simone di Fresco', email: null },
    { name: 'Lucia', email: null },
    { name: 'Andreas di Fresco', email: null },
    { name: 'Carla Messini', email: null },
    { name: 'Massimo Giarelli', email: null },
    { name: 'Gabriele Giarelli', email: null },
    { name: 'Martina Chinello', email: null },
    { name: 'Sara Giarelli', email: null },
    { name: 'Lorenzo Giarelli', email: null },
    { name: 'Isora Poggesi', email: null },
    { name: 'Carlo Messini', email: null },
    { name: 'Anna', email: null },
    { name: 'Francesco Messini', email: null },
    { name: 'Silvia', email: null },
    { name: 'Alberto Messini', email: null },
    { name: 'Noemi', email: null },
    { name: 'Lucrezia Messini', email: null },
    { name: 'Marta Messini', email: null },
    { name: 'Giuseppe Pisano', email: null },
    { name: 'Ilaria Pisano', email: null },
    { name: 'Andrea Biagini', email: null },
    { name: 'Camilla Pantaleoni', email: null },
    { name: 'Federico Massaccesi', email: null },
    { name: 'Ludovica Paradisi', email: null },
    { name: 'Alessio Cambiotti', email: null },
    { name: 'Marco Fiorucci', email: null },
    { name: 'Patrizia Bruni', email: null },
    { name: 'Matteo Fiorucci', email: null },
    { name: 'Sara Rosini', email: null },
    { name: 'Noemi Fiorucci', email: null },
    { name: 'Elisa Fiorucci', email: null },
    { name: 'Roberta Fiorucci', email: null },
    { name: 'Lorena Fiorucci', email: null },
    { name: 'Francesco Lattanzi', email: null },
    { name: 'Alessia Giombolini', email: null },
    { name: 'Tiziana Testa', email: null },
    { name: 'Vincenzo Gionangeli', email: null },
    { name: 'Michela Bruno', email: null },
    { name: 'Gianluca de Lorenzo', email: null },
    { name: 'Riccardo de Lorenzo', email: null },
    { name: 'Nicolò de Lorenzo', email: null },
    { name: 'Diletta Bigini', email: null },
    { name: 'Giovanni Buini', email: null },
    { name: 'Anna Agostinelli', email: null },
    { name: 'Michele Meniconi', email: null },
    { name: 'Lorenzo Casuscelli', email: null },
    { name: 'Nicolò Poltroneri', email: null },
    { name: 'Marta Pero', email: null },
    { name: 'Lena Schepers', email: null },
    { name: 'Veronica Benedetti', email: null },
    { name: 'Lorenzo Catanzani', email: null },
    { name: 'Lavinia Gigliarelli', email: null },
    { name: 'Francesco Marsili', email: null },
    { name: 'Linda Bachiorri', email: null },
    { name: 'Matteo Bernardini', email: null },
    { name: 'Amaia Pelucca', email: null },
    { name: 'Lorenzo Moscatelli', email: null },
    { name: 'Anna Chiara Dozzini', email: null },
    { name: 'Gregorio Briatico', email: null },
    { name: 'Claudia Russo', email: null },
    { name: 'Alessandro Busco', email: null },
    { name: 'Paolo Busco', email: null },
    { name: 'Martina Bigagli', email: null },
    { name: 'Stefania Azzerboni', email: null },
    { name: 'Elisabetta Meschini', email: null },
    { name: 'Luca Battistoni', email: null },
    { name: 'Cecilia Crisanti', email: null },
    { name: 'Nicola Gramaccioni', email: null },
    { name: 'Lucia Galletti', email: null },
    { name: 'Luisa Tini', email: null },
    { name: 'Ambra Gargiulo', email: null },
    { name: 'Angelo d\'Abondo', email: null },
    { name: 'Daniela Mazzella', email: null },
    { name: 'Riccardo Concia', email: null },
    { name: 'Cesare Coppe', email: null },
    { name: 'Giulia Vinicola', email: null },
    { name: 'Francesco', email: null },
    { name: 'Elena Mariani', email: null },
    { name: 'Simone Ossola', email: null },
    { name: 'Diego Ossola', email: null },
    { name: 'Martina Saladini', email: null },
    { name: 'Pedro', email: null },
    { name: 'Diego', email: null },
    { name: 'Andrea Patiti', email: null },
    { name: 'Federico Patiti', email: null },
    { name: 'Valentina Greco', email: null },
    { name: 'Filippo Patiti', email: null },
    { name: 'Roberto Giaimo', email: null },
    { name: 'Arianna', email: null },
    { name: 'Fabio Giaimo', email: null },
    { name: 'Mauro Patiti', email: null },
    { name: 'Francesca Orfei', email: null },
    { name: 'Sergio Malinconici', email: null },
    { name: 'Carla Castrini', email: null },
    { name: 'Aaron Malinconici', email: null },
    { name: 'Cristina Salari', email: null },
];

async function main() {
    console.log('Seeding guests...');
    
    for (const guest of guests) {
        await prisma.guest.upsert({
            where: { name: guest.name },
            update: {},
            create: {
                name: guest.name,
                email: guest.email
            }
        });
    }
    
    console.log(`Seeded ${guests.length} guests`);
}

main()
    .catch((e) => {
        console.error(e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
